engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    exclude_fingerprints:
    - 580ec239bc6e53e62cd63ce219b812e6
    - 39dfc9669aec43e3e76abb09d3b5fcc1
    - 016d5b320f02cb900b27631f3c7c0a20
    checks:
      Rubocop/Rails/Output:
        enabled: false
ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/
